<a href="https://colab.research.google.com/github/nladocsi/DS3001_F25_Project/blob/main/Milestone3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Milestone 3
## Setting Up and Uploading Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./adult24.csv')
print(df.shape, '\n')
df.head()

(32629, 630)

,RATCAT_A,INCTCFLG_A,IMPINCFLG_A,PPSU,PSTRAT,WLKLEISTC_A,WLKTRANTC_A,HISPALLP_A,RACEALLP_A,ANYDIFF_A,...,LSATIS4_A,PHSTAT_A,HHSTAT_A,INTV_MON,RECTYPE,IMPNUM_A,AVGNUMCIG_A,WTFA_A,HHX,POVRATTC_A
0,9,0,2,2,122,NaN,NaN,2,1,2,...,1,1,1,1,10,1,30,5780.565,H067658,2.82
1,8,0,0,2,122,20.0,NaN,2,1,2,...,2,2,1,1,10,1,20,3994.244,H076577,2.01
2,7,0,0,2,122,30.0,NaN,2,1,1,...,1,2,1,1,10,1,20,6636.755,H019335,1.90
3,12,0,0,2,122,10.0,NaN,2,1,1,...,2,3,1,1,10,1,01,13767.420,H012701,4.48
4,14,0,0,1,115,NaN,NaN,3,2,1,...,2,3,1,1,10,1,NaN,18880.030,H049678,6.37

## Cleaning Data

In [3]:
#Keeping Only Columns of Interest
cols = ['GESDIB_A', 'PREDIB_A', 'DIBEV_A', 'DIBTYPE_A',
        'DIBAGETC_A', 'FDSRUNOUT_A', 'FDSLAST_A',
        'FDSHUNGRY_A', 'SEX_A', 'REGION', 'RACEALLP_A',
        'RATCAT_A', 'EDUCP_A', 'PHSTAT_A', 'WLKLEIS_A']
df = df[cols]
print(df.shape, '\n')
df.head()

(32629, 15)

,GESDIB_A,PREDIB_A,DIBEV_A,DIBTYPE_A,DIBAGETC_A,FDSRUNOUT_A,FDSLAST_A,FDSHUNGRY_A,SEX_A,REGION,RACEALLP_A,RATCAT_A,EDUCP_A,PHSTAT_A,WLKLEIS_A
0,NaN,2,2,NaN,NaN,3,3,NaN,1,3,1,9,5,1,2.0
1,NaN,2,2,NaN,NaN,3,3,NaN,1,3,1,8,5,2,1.0
2,NaN,2,2,NaN,NaN,3,3,NaN,1,3,1,7,5,2,1.0
3,NaN,2,2,NaN,NaN,3,2,2.0,1,3,1,12,4,3,1.0
4,2.0,2,2,NaN,NaN,3,3,NaN,2,3,2,14,9,3,2.0

In [ ]:
#Creating Food Insecurity Variable

def recode_food(v):
  if v in [1, 2]:
    return 1
  if v == 3:
    return 2
  if v in [7, 8, 9]:
    return v
  return np.nan

food_insecurity = ['FDSRUNOUT_A', 'FDSLAST_A', 'FDSHUNGRY_A']

for var in food_insecurity:
  df[var] = df[var].apply(recode_food)

df['food_insecurity'] = df[food_insecurity].sum(axis=1)

In [4]:
#Creating one variable for diabetes
df[["PREDIB_A", "GESDIB_A", "DIBEV_A"]] = df[["PREDIB_A", "GESDIB_A", "DIBEV_A"]].replace([7, 8, 9], np.nan)


df["DIAB_ANY"] = np.where(
    (df[["PREDIB_A", "GESDIB_A", "DIBEV_A"]] == 1).any(axis=1), 1,
    np.where(
        (df[["PREDIB_A", "GESDIB_A", "DIBEV_A"]] == 2).any(axis=1), 0,
        np.nan))
df = df.drop(columns=["PREDIB_A", "GESDIB_A", "DIBEV_A"])

df.head()

,DIBTYPE_A,DIBAGETC_A,FDSRUNOUT_A,FDSLAST_A,FDSHUNGRY_A,SEX_A,REGION,RACEALLP_A,RATCAT_A,EDUCP_A,PHSTAT_A,WLKLEIS_A,DIAB_ANY
0,NaN,NaN,3,3,NaN,1,3,1,9,5,1,2.0,0.0
1,NaN,NaN,3,3,NaN,1,3,1,8,5,2,1.0,0.0
2,NaN,NaN,3,3,NaN,1,3,1,7,5,2,1.0,0.0
3,NaN,NaN,3,2,2.0,1,3,1,12,4,3,1.0,0.0
4,NaN,NaN,3,3,NaN,2,3,2,14,9,3,2.0,0.0

## Building Model